// leave off @2x/@3x
const images = {
  userProfileIcon: require('../assets/imgs/manUser.png'),
  registrationFinishImage: require('../assets/imgs/hotelBookedIllustration.png'),
  filterIcon: require('../assets/imgs/preferencesCircle.png'),
  searchIcon: require('../assets/imgs/search.png'),
  greenLocationIcon: require('../assets/imgs/placeholder2.png'),
  locationFlagCardIcon: require('../assets/imgs/path114.png'),
  watchFlagCardIcon: require('../assets/imgs/group9054.png'),
  favorateIcon: require('../assets/imgs/star.png'),
  testCardImage: require('../assets/imgs/Group_85.png'),
  mapIconForList: require('../assets/imgs/mapViewIcon.png'),
  penIcon: require('../assets/imgs/pen-01.png'),
  gbsIcon: require('../assets/imgs/icons-gps.png'),
  mapCardImage: require('../assets/imgs/Group_85.png'),
  userLocationIcon: require('../assets/imgs/userLocationIcon.png'),
  addingImageCircle: require('../assets/imgs/addImage.png'),
  cameraIcon: require('../assets/imgs/imageAddButton.png'),
  imageDeleteCloseIcon: require('../assets/imgs/close1.png'),
  addIcon: require('../assets/imgs/addProperty1.png'),
  whatsappIcon: require('../assets/imgs/whatsapp.png'),
  shareIcon: require('../assets/imgs/share.png'),
  callIcon: require('../assets/imgs/call.png'),
  kitchenIcon: require('../assets/imgs/kitchen3.png'),
  sofaIcon: require('../assets/imgs/sofa.png'),
  bathRoomIcon: require('../assets/imgs/bathtub.png'),
  sleepIcon: require('../assets/imgs/beedroon360Degree.png'),
  checkBoxIcon: require('../assets/imgs/checklistCheckedBox.png'),
  starDetail: require('../assets/imgs/star.png'),
  scopeDetail: require('../assets/imgs/scope.png'),
  gifTest: require('../assets/imgs/giphy.gif'),
  QRImage: require('../assets/imgs/qrCode.png'),
  HectarBetIcon: require('../assets/imgs/hectar-logo3x.png'),
};

export default images;
